version: "3.3"
networks:
  lnnet:

services:
  # The dev container is not actually used, it is just handy to run `docker-compose up dev` to start all services
  dev: 
    image: alpine:3.7
    command: [ "/bin/sh", "-c", "trap : TERM INT; while :; do echo Ready to code and debug like a rockstar!!!; sleep 2073600; done & wait" ]
    links:
      - c-lightning
      - lnd
      - eclair
      - lnd2
      # - postgres

  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: crypto/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always
  
  c-lightning:
    container_name: c-lightning
    build:
      context: c-lightning
    image: crypto/c-lightning:latest
    networks:
      - lnnet
    expose:
      - "9735"
      - "9835"
    restart: always
    depends_on:
      - bitcoind

  lnd:
    container_name: lnd
    build:
      context: lnd
    image: crpyto/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
      - "10009"
    restart: always
    depends_on:
      - bitcoind

  eclair:
    container_name: eclair
    build:
      context: eclair
    image: crypto/eclair
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
    depends_on:
      - bitcoind

  lnd2:
    container_name: lnd2
    build:
      context: lnd
    image: crpyto/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
      - "10009"
    restart: always
    depends_on:
      - bitcoind

  # postgres:
  #   container_name: postgres
  #   image: postgres:9.6.5
  #   ports:
  #     - "39375:5432"
  #   expose:
  #     - "5432"



